# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: This is a  very useful blog for WBCS aspirants
email:  mukherjeesayantani87@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A warm welcome to my blog. Myself Dr Mukherjee, who is a practicing dentist and also helps folks to clear
  West Bengal Civil Service exam. This is more of my passion and over the last couple of years , I have mentored 
  a few students to clear the exam and the interview successfully. Hence I decided to start blogging to further
  spread my teachings to a wider audience. Hope you find it interesting and of course helpful. Looking forward
  to your feedback !!!
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: msayantani
github_username:  msayantani

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
